security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4 # Valeur la plus basse possible pour bcrypt
            time_cost: 3 # Valeur la plus basse possible pour argon
            memory_cost: 10 # Valeur la plus basse possible pour argon

    providers:
        users:
            entity:
                class: App\Entity\UserLogin
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: users
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home.plan_mariage # Rediriger ici après la connexion réussie
            logout :
                path : app_logout
                target: home.plan_mariage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
