security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4 # Valeur la plus basse possible pour bcrypt
            time_cost: 3 # Valeur la plus basse possible pour argon
            memory_cost: 10 # Valeur la plus basse possible pour argon

    providers:
        users:
            entity:
                class: App\Entity\UserLogin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users
            form_login:
                login_path: app_login
                check_path: app_login

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }


