vich_uploader:
    db_driver: orm
    storage: flysystem
    
    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /uploads/activity
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
